### ISSUE TITLE
[FEAT] iOS 3주차 과제

### ISSUE THREAD

**Issue by noah0316** [29th-WE-SOPT-iOS-Part/HongSeungHyun#11]
## 📌  Feature Issue

3주차 과제는 TableView와 CollectionView의 적용입니다!
## 📝  To-do

- [x] 테이블 뷰 컨트롤러 생성 및 연결
- [x] 테이블 뷰 셀 생성
- [x] 테이블 뷰 등록 및 호출
- [x] 컬렉션 뷰 컨트롤러 생성 및 연결
- [x] 컬렉션 뷰 등록 및 호출
- [x] 상단바 오토레이아웃
- [x] 도전과제
