### ISSUE TITLE
[FEAT] iOS 4주차 과제

### ISSUE THREAD

**Issue by noah0316** [29th-WE-SOPT-iOS-Part/HongSeungHyun#18]
## 📌  Feature Issue
4주차 과제는 처음만들었던 로그인 회원가입에 실제 API를 붙여보기입니다!
## 📝  To-do

▶️ 프로필 화면전환
- [x] 시작 스토리보드 변경
- [x] 프로필을 눌렀을 때 로그인 flow로 화면전환

▶️ 로그인
- [x] 다음 버튼 클릭 시 서버와 통신을 하고 서버의 응답에 따른 alert 띄우기 

▶️ 회원가입
- [x] 다음 버튼을 눌렀을 때 서버와 통신을 하고 서버의 응답에 따른 alert 띄우기
