### ISSUE TITLE
[FEAT] iOS 7주차 과제

### ISSUE THREAD

**Issue by noah0316** [29th-WE-SOPT-iOS-Part/HongSeungHyun#21]
## 📌  Feature Issue
7주차 과제는 데이터 연결 심화와 UIGestureRecognizer입니다!

## 📝  To-do

- [x] Home imageView에 tap gesture recognizer 추가하기
- [x] imageView가 tap되었을 때 화면전환하며 데이터 전달하기
- [x] 전환된 화면 dismiss 기능 추가하기
