### ISSUE TITLE
[FEAT] iOS 1주차 과제

### ISSUE THREAD

**Issue by noah0316** [29th-WE-SOPT-iOS-Part/HongSeungHyun#3]
## 📌 Feature Issue

1주차 과제는 로그인, 회원가입, 확인화면 

UI 구성과 화면전환 그리고 데이터 전달입니다!

## 📝 To-do

▶️ UI 구성하기

- [x]  로그인 화면 UI 구성하기 6567b809a5b54ff69de5f1190b9fc92c897bad9a
- [x]  회원가입 화면 UI 구성하기 c74cc23a6c25e62cc966abda8c10b6e65a10dae0
- [x]  확인 화면 UI 구성하기 bec3f88d4fc5a80c6aa0cd4a4db1e39c382e7916

▶️ 화면 전환하기

- [x]  로그인 화면 → 회원가입 화면 으로 push로 화면전환하기 1b996a014dc5a920db49ed57598fb395d5bde97c
- [x]  로그인 화면 → 확인 화면 으로 present로 화면전환하기 3f8e5e27d879869ff13a253295203a1f6ea4359f
- [x]  회원가입 화면 → 확인 화면 으로 present로 화면전환하기 8efe628cfeab7b49f2f021505723b74eec38846d

▶️ 기능 구현하기

- [x]  로그인 화면에서 적은 이름을 확인 화면에서 띄우기 6cdc6a1e19fa4c4126c101dc55f9298066b9203f
- [x]  회원가입 화면에서 적은 이름을 확인 화면에서 띄우기 bd696faa53f8b5688b66c27c2311a18368f3392e

▶️ 🔥도전과제

- [x]  로그인화면과 회원가입 화면에서 3개의 textfield값이 모두 채워지면 다음 버튼이 활성화되는 로직 구현하기 64a8864bf4634dc1915bbfd32c526a0402132c5f
- [x]  회원가입 화면에서 비밀번호 표시를 누를 경우 비밀번호가 표시되도록 구현하기 043210cea5547cea7caf8b986b8c5b5fac16bbde
